// Dice.cpp created from Lab4.pdf for CS162 Winter 2015
// File generated by David Rigert

#include <cstdlib>
#include "Dice.hpp"

// Use a global seed value for all Dice objects and increment it each use.
// This prevents two objects created in rapid succession from having 
// the same seed value.
unsigned Dice::seed = static_cast<unsigned>(time(NULL));

Dice::Dice()
{
    numSides = 6;
    srand(seed++); // Seeds random number generator
}

Dice::Dice(int numSides)
{
    this->numSides = numSides;
    srand(seed++); // Seeds random number generator
}

int Dice::rollDice() const
{
    return (rand() % numSides) + 1;
}
