// Dice.hpp created from Lab4.pdf for CS162 Winter 2015
// File generated by David Rigert
// Modified on 2/14/2015 for Assignment 3

#ifndef DICE_HPP
#define DICE_HPP

#include <ctime>

class Dice
{
public:
    Dice();
    Dice( int numSides);
    int rollDice() const;
private:
    int numSides;
    static unsigned seed;
};
#endif
