// Dice.hpp created from Lab4.pdf for CS162 Winter 2015
// File generated by David Rigert

#ifndef DICE_HPP
#define DICE_HPP
class Dice
{
public:
    Dice();
    Dice( int numSides);
    virtual int rollDice() const;
protected:
    int numSides;
};

int rollTwoDice(const Dice &, const Dice &);
#endif
